cdcservice:
  build: ./eventuate-tram-cdc-mysql-service
  ports:
    - "8099:8080"
  links:
    - mysqlbinlogpipeline
    - postgrespollingpipeline
    - postgreswalpipeline
    - kafka
    - zookeeper
  environment:
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ACTIVEMQ_URL: tcp://${DOCKER_HOST_IP}:61616
    RABBITMQ_URL: ${DOCKER_HOST_IP}
    EVENTUATE_CDC_PIPELINE_PROPERTIES: >
      [{"type":"eventuate-local-mysql-binlog",
      "dataSourceUrl":"jdbc:mysql://${DOCKER_HOST_IP}:3306/eventuate",
      "dataSourceUserName":"mysqluser",
      "dataSourcePassword":"mysqlpw",
      "dataSourceDriverClassName":"com.mysql.jdbc.Driver",
      "leadershipLockPath":"/eventuatelocal/cdc/leader/pipeline/1",
      "mySqlBinLogClientName":"DbLog1",
      "dbHistoryTopicName":"db.history.topic1",
      "cdcDbUserName":"root",
      "cdcDbPassword":"rootpassword"},
      {"type":"eventuate-local-event-polling",
      "dataSourceUrl":"jdbc:postgresql://${DOCKER_HOST_IP}/eventuate",
      "dataSourceUserName":"eventuate",
      "dataSourcePassword":"eventuate",
      "dataSourceDriverClassName":"org.postgresql.Driver",
      "leadershipLockPath":"/eventuatelocal/cdc/leader/pipeline/2",
      "mySqlBinLogClientName":"DbLog2",
      "dbHistoryTopicName":"db.history.topic2"},
      {"type":"eventuate-local-postgres-wal",
      "dataSourceUrl":"jdbc:postgresql://${DOCKER_HOST_IP}:5433/eventuate",
      "dataSourceUserName":"eventuate",
      "dataSourcePassword":"eventuate",
      "dataSourceDriverClassName":"org.postgresql.Driver",
      "postgresReplicationSlotName":"eventuate_slot",
      "leadershipLockPath":"/eventuatelocal/cdc/leader/pipeline/3"},
      {"type":"eventuate-tram-mysql-binlog",
      "dataSourceUrl":"jdbc:mysql://${DOCKER_HOST_IP}:3306/eventuate",
      "dataSourceUserName":"mysqluser",
      "dataSourcePassword":"mysqlpw",
      "dataSourceDriverClassName":"com.mysql.jdbc.Driver",
      "leadershipLockPath":"/eventuatelocal/cdc/leader/pipeline/4",
      "mySqlBinLogClientName":"DbLog3",
      "dbHistoryTopicName":"db.history.topic3",
      "cdcDbUserName":"root",
      "cdcDbPassword":"rootpassword"},
      {"type":"eventuate-tram-event-polling",
      "dataSourceUrl":"jdbc:postgresql://${DOCKER_HOST_IP}/eventuate",
      "dataSourceUserName":"eventuate",
      "dataSourcePassword":"eventuate",
      "dataSourceDriverClassName":"org.postgresql.Driver",
      "leadershipLockPath":"/eventuatelocal/cdc/leader/pipeline/5"},
      {"type":"eventuate-tram-postgres-wal",
      "dataSourceUrl":"jdbc:postgresql://${DOCKER_HOST_IP}:5433/eventuate",
      "dataSourceUserName":"eventuate",
      "dataSourcePassword":"eventuate",
      "dataSourceDriverClassName":"org.postgresql.Driver",
      "postgresReplicationSlotName":"eventuate_slot2",
      "leadershipLockPath":"/eventuatelocal/cdc/leader/pipeline/6",
      "mySqlBinLogClientName":"DbLog4",
      "dbHistoryTopicName":"db.history.topic4"}]